# -*- mode: ruby -*-
# vi: set ft=ruby :

$npm_install = <<SCRIPT
     cd /home/vagrant/app/ && npm install
SCRIPT

$npm_global = <<SCRIPT
  npm install -g grunt-cli
SCRIPT


$gem_global = <<SCRIPT
  gem install compass
SCRIPT

$goto_project = <<SCRIPT
   cd /home/vagrant/app/
SCRIPT

$build = <<SCRIPT
    cd /home/vagrant/app/ && grunt build
SCRIPT

$run_server = <<SCRIPT
    cd /home/vagrant/app/ && grunt dev
SCRIPT

VAGRANTFILE_API_VERSION = "2"
require 'rbconfig'


  ports = JSON.load('../ports.json')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"

  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network :forwarded_port, guest: ports.dev, host: ports.vir_dev
  config.vm.network :forwarded_port, guest: ports.test, host: ports.vir_test
  config.vm.network :forwarded_port, guest: ports.live, host: ports.vir_live

  config.vm.synced_folder "../", "/home/vagrant/app"


  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "nodejs"
    chef.json = {
        "nodejs" => {
            "version" => "0.10.0"
            # uncomment the following line to force
            # recent versions (> 0.8.5) to be built from
            # the source code
            # , "from_source" => true
        }
    }
  end

  config.vm.provision :shell, :inline => $npm_global
  config.vm.provision :shell, :inline => $gem_global
  config.vm.provision :shell, :inline => $npm_install
  config.vm.provision :shell, :inline => $build
  config.vm.provision :shell, :inline => $run_server


end
